DEBUG:root:This message should go to the log file
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:flask.app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 22, in load_json
    return json.loads(open(filename).read())
FileNotFoundError: [Errno 2] No such file or directory: 'root.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 52, in index
    load_json(hargrave_conf.ROOT_JSON_FILE)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 25, in load_json
    log("Creating root json file")
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 18, in log
    logger.debug(message)
NameError: name 'logger' is not defined
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:52:15] "GET / HTTP/1.1" 500 -
ERROR:flask.app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 22, in load_json
    return json.loads(open(filename).read())
FileNotFoundError: [Errno 2] No such file or directory: 'root.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 52, in index
    load_json(hargrave_conf.ROOT_JSON_FILE)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 25, in load_json
    log("Creating root json file")
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 18, in log
    logger.debug(message)
NameError: name 'logger' is not defined
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:52:16] "GET / HTTP/1.1" 500 -
ERROR:flask.app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 22, in load_json
    return json.loads(open(filename).read())
FileNotFoundError: [Errno 2] No such file or directory: 'root.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 52, in index
    load_json(hargrave_conf.ROOT_JSON_FILE)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 25, in load_json
    log("Creating root json file")
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 18, in log
    logger.debug(message)
NameError: name 'logger' is not defined
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:52:16] "GET / HTTP/1.1" 500 -
ERROR:flask.app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 22, in load_json
    return json.loads(open(filename).read())
FileNotFoundError: [Errno 2] No such file or directory: 'root.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 52, in index
    load_json(hargrave_conf.ROOT_JSON_FILE)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 25, in load_json
    log("Creating root json file")
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 18, in log
    logger.debug(message)
NameError: name 'logger' is not defined
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:52:16] "GET / HTTP/1.1" 500 -
ERROR:flask.app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 22, in load_json
    return json.loads(open(filename).read())
FileNotFoundError: [Errno 2] No such file or directory: 'root.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 52, in index
    load_json(hargrave_conf.ROOT_JSON_FILE)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 25, in load_json
    log("Creating root json file")
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 18, in log
    logger.debug(message)
NameError: name 'logger' is not defined
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:52:16] "GET / HTTP/1.1" 500 -
ERROR:flask.app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 22, in load_json
    return json.loads(open(filename).read())
FileNotFoundError: [Errno 2] No such file or directory: 'root.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 52, in index
    load_json(hargrave_conf.ROOT_JSON_FILE)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 25, in load_json
    log("Creating root json file")
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 18, in log
    logger.debug(message)
NameError: name 'logger' is not defined
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:52:17] "GET / HTTP/1.1" 500 -
ERROR:flask.app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 22, in load_json
    return json.loads(open(filename).read())
FileNotFoundError: [Errno 2] No such file or directory: 'root.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 52, in index
    load_json(hargrave_conf.ROOT_JSON_FILE)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 25, in load_json
    log("Creating root json file")
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 18, in log
    logger.debug(message)
NameError: name 'logger' is not defined
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:52:18] "GET / HTTP/1.1" 500 -
ERROR:flask.app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 22, in load_json
    return json.loads(open(filename).read())
FileNotFoundError: [Errno 2] No such file or directory: 'root.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 52, in index
    load_json(hargrave_conf.ROOT_JSON_FILE)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 25, in load_json
    log("Creating root json file")
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 18, in log
    logger.debug(message)
NameError: name 'logger' is not defined
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:52:18] "GET / HTTP/1.1" 500 -
ERROR:flask.app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 22, in load_json
    return json.loads(open(filename).read())
FileNotFoundError: [Errno 2] No such file or directory: 'root.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 52, in index
    load_json(hargrave_conf.ROOT_JSON_FILE)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 25, in load_json
    log("Creating root json file")
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 18, in log
    logger.debug(message)
NameError: name 'logger' is not defined
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:52:18] "GET / HTTP/1.1" 500 -
DEBUG:root:This message should go to the log file
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:flask.app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 22, in load_json
    return json.loads(open(filename).read())
FileNotFoundError: [Errno 2] No such file or directory: 'root.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 52, in index
    load_json(hargrave_conf.ROOT_JSON_FILE)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 25, in load_json
    log("Creating root json file")
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 18, in log
    logger.debug(message)
NameError: name 'logger' is not defined
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:52:37] "GET / HTTP/1.1" 500 -
ERROR:flask.app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 22, in load_json
    return json.loads(open(filename).read())
FileNotFoundError: [Errno 2] No such file or directory: 'root.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 52, in index
    load_json(hargrave_conf.ROOT_JSON_FILE)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 25, in load_json
    log("Creating root json file")
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 18, in log
    logger.debug(message)
NameError: name 'logger' is not defined
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:52:38] "GET / HTTP/1.1" 500 -
ERROR:flask.app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 22, in load_json
    return json.loads(open(filename).read())
FileNotFoundError: [Errno 2] No such file or directory: 'root.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 52, in index
    load_json(hargrave_conf.ROOT_JSON_FILE)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 25, in load_json
    log("Creating root json file")
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 18, in log
    logger.debug(message)
NameError: name 'logger' is not defined
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:52:39] "GET / HTTP/1.1" 500 -
ERROR:flask.app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 22, in load_json
    return json.loads(open(filename).read())
FileNotFoundError: [Errno 2] No such file or directory: 'root.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 52, in index
    load_json(hargrave_conf.ROOT_JSON_FILE)
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 25, in load_json
    log("Creating root json file")
  File "/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py", line 18, in log
    logger.debug(message)
NameError: name 'logger' is not defined
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:52:39] "GET / HTTP/1.1" 500 -
DEBUG:root:This message should go to the log file
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
DEBUG:root:This message should go to the log file
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:44] "GET / HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:44] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:44] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:44] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:45] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:45] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:45] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:45] "GET / HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:45] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:45] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:45] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:45] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:45] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:45] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:45] "GET / HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:45] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:45] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:45] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:45] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:45] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:45] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
DEBUG:root:This message should go to the log file
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:56] "GET / HTTP/1.1" 200 -
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:53:57] "GET / HTTP/1.1" 200 -
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:54:19] "GET / HTTP/1.1" 200 -
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:55:27] "GET / HTTP/1.1" 200 -
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:56:27] "GET / HTTP/1.1" 200 -
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:56:28] "GET / HTTP/1.1" 200 -
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:56:39] "GET / HTTP/1.1" 200 -
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 11:56:40] "GET / HTTP/1.1" 200 -
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 12:51:41] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 12:51:41] "GET /css/bootstrap.min.css HTTP/1.1" 304 -
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 12:51:53] "GET / HTTP/1.1" 200 -
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 12:51:53] "GET / HTTP/1.1" 200 -
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 12:51:53] "GET / HTTP/1.1" 200 -
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 12:51:57] "GET / HTTP/1.1" 200 -
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 12:52:14] "GET / HTTP/1.1" 200 -
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 12:52:16] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
DEBUG:root:This message should go to the log file
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
DEBUG:root:This message should go to the log file
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:17] "GET / HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:17] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:17] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:17] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:17] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:17] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:17] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:18] "GET / HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:18] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:18] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:18] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:18] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:18] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:18] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:18] "GET / HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:18] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:18] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:18] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:18] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:19] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:19] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:34] "GET / HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:34] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:34] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:34] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:34] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:34] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:34] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:35] "GET / HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:35] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:35] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:35] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:35] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:35] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:06:35] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:07:34] "GET / HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:07:34] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:07:34] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:07:34] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:07:34] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:07:34] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:07:34] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
DEBUG:root:Creating root json file
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:07:35] "GET / HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:07:35] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:07:35] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:07:35] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:07:35] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:07:35] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 13:07:35] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:48:19] "GET / HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:48:19] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:48:19] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:48:19] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:48:19] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:48:19] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:48:19] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:48:19] "GET / HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:48:19] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:48:19] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:48:19] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:48:19] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:48:19] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:48:19] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:48:20] "GET / HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:48:20] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:48:20] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:48:20] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:48:20] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:48:20] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:48:20] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:00] "GET / HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:00] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:00] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:00] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:00] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:01] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:01] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:01] "GET / HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:01] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:01] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:01] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:01] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:01] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:01] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:34] "GET / HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:35] "GET / HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:49] "GET / HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:49] "GET / HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:50] "GET / HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:50] "GET / HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:54] "GET / HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:54] "GET / HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:49:54] "GET / HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:50:00] "GET / HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:50:07] "GET / HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:50:07] "GET / HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:50:35] "GET / HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:50:36] "GET / HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:51:55] "GET / HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:52:14] "GET / HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:52:15] "GET / HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:52:16] "GET / HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:52:16] "GET / HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:52:31] "GET / HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:52:32] "GET / HTTP/1.1" 200 -
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:52:32] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave_conf.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
DEBUG:root:Root json file blank.
INFO:werkzeug:127.0.0.1 - - [22/Sep/2018 15:54:35] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
INFO:werkzeug: * Detected change in '/home/arthurdent/NAS/primary_a/Projects/hargrave/files/hargrave/hargrave.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 180-800-348
